version: 0.0
os: linux

files:
  - source:  /
    destination: /home/deploy-user/cicd
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: deploy-user
    group: deploy-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: deploy-user