services:
  bts-backend-db:
    container_name: bts-backend-db
    image: mysql
    environment:
      MYSQL_DATABASE: bts
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: bangtal-boys
    networks:
      - bts-backend
    volumes:
      - bts-backend-db:/var/lib/mysql
      - bts-backend-db-ini:/etc/mysql/conf.d
    ports:
      - "3307:3307"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]

  bts-backend:
    container_name: bts-backend
    image: bts-backend
    restart: always
    networks:
      - bts-backend
    ports:
      - "8881:8080"
    depends_on:
      - bts-backend-db

networks:
  bts-backend:
    driver: bridge
volumes:
  bts-backend-db:
    name: bts-backend-db
    external: false
  bts-backend-db-ini:
    name: bts-backend-db-ini
    external: false
