services:
  bts-backend:
    image: ghcr.io/bts-escaperoom/bts-backend:${IMAGE_TAG}
    restart: always
    networks:
      - bts-backend
    ports:
      - "8881:8080"

networks:
  bts-backend:
    driver: bridge