spring:
  security:
    jwt:
      secret-key: 37e5e6213096155c93ce0d832fc2f1f5a0faca5785f893fa4eb9b9d4676f2404
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6314ef9de4168d995d3c4c4c308f8fef
            client-secret: jte1OyJD8wDmQdKWjh3E6mRNjLrC91y2
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/auth/kakao/callback"
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정